# Autogenered by /Users/mario/Documents/projects/msml/python/msml/_ffi_cdecl_generator.py 2024-10-17 16:44:45.081828, do NOT edit!

__MSML_CDECLS: str = '''

typedef struct msml_ctx_info_t msml_ctx_info_t;
typedef struct msml_ctx_t msml_ctx_t;
typedef struct msml_dtype_info_t msml_dtype_info_t;
typedef struct msml_tensor_t msml_tensor_t;
typedef struct msml_compute_graph_t msml_compute_graph_t;

typedef int msml_exec_mode_t;
typedef int msml_prng_algorithm_t;
typedef int msml_dtype_t;
typedef int msml_desired_color_channels_t;
typedef int msml_op_t;
typedef int msml_graph_eval_order_t;

extern   void* msml_default_allocator_impl(void* blk, size_t size);
extern   msml_ctx_t* msml_ctx_create(const msml_ctx_info_t* info);
extern   msml_ctx_t* msml_ctx_create2(size_t pool_chunk_size);
extern   void* msml_ctx_pool_alloc(msml_ctx_t* ctx, size_t size);
extern   void* msml_ctx_pool_alloc_aligned(msml_ctx_t* ctx, size_t size, size_t align);
extern   size_t msml_ctx_total_allocated_pool_memory(const msml_ctx_t* ctx);
extern   msml_exec_mode_t msml_ctx_get_exec_mode(const msml_ctx_t* ctx);
extern   void msml_ctx_set_exec_mode(msml_ctx_t* ctx, msml_exec_mode_t mode);
extern   msml_prng_algorithm_t msml_ctx_get_prng_algorithm(const msml_ctx_t* ctx);
extern   void msml_ctx_set_prng_algorithm(msml_ctx_t* ctx, msml_prng_algorithm_t algorithm, uint64_t seed);
extern   const char* msml_ctx_get_os_name(const msml_ctx_t* ctx);
extern   const char* msml_ctx_get_cpu_name(const msml_ctx_t* ctx);
extern   uint32_t msml_ctx_get_cpu_virtual_cores(const msml_ctx_t* ctx);
extern   uint32_t msml_ctx_get_cpu_physical_cores(const msml_ctx_t* ctx);
extern   uint32_t msml_ctx_get_cpu_sockets(const msml_ctx_t* ctx);
extern   uint64_t msml_ctx_get_physical_memory_total(const msml_ctx_t* ctx);
extern   uint64_t msml_ctx_get_physical_memory_free(const msml_ctx_t* ctx);
extern   bool msml_ctx_is_numa_system(const msml_ctx_t* ctx);
extern   void msml_ctx_destroy(msml_ctx_t* ctx);
extern   const msml_dtype_info_t* msml_get_dtype_info(msml_dtype_t type);
extern   const char* msml_op_get_name(msml_op_t op);
extern   const char* msml_op_get_mnemonic(msml_op_t op);
extern   uint8_t msml_op_get_argcount(msml_op_t op);
extern   msml_tensor_t* msml_tensor_create_1d(msml_ctx_t* ctx, msml_dtype_t type, int64_t d1);
extern   msml_tensor_t* msml_tensor_create_2d(msml_ctx_t* ctx, msml_dtype_t type, int64_t d1, int64_t d2);
extern   msml_tensor_t* msml_tensor_create_3d(msml_ctx_t* ctx, msml_dtype_t type, int64_t d1, int64_t d2, int64_t d3);
extern   msml_tensor_t* msml_tensor_create_4d(msml_ctx_t* ctx, msml_dtype_t type, int64_t d1, int64_t d2, int64_t d3, int64_t d4);
extern   msml_tensor_t* msml_tensor_operator(msml_ctx_t* ctx, msml_op_t op, msml_tensor_t** inputs, uint32_t n_inputs);
extern   void msml_tensor_copy_buffer_from(msml_tensor_t* tensor, const void* data, size_t size);
extern   void msml_tensor_fill(msml_tensor_t* tensor, float x);
extern   void msml_tensor_fill_random(msml_tensor_t* tensor, float min, float max);
extern   size_t msml_tensor_get_memory_usage(const msml_tensor_t* tensor);
extern   void msml_tensor_print(const msml_tensor_t* tensor, bool with_data);
extern   void msml_tensor_set_name(msml_tensor_t* tensor, const char* name);
extern   void msml_tensor_fmt_name(msml_tensor_t* tensor, const char* fmt, ...);
extern   const char* msml_tensor_get_name(const msml_tensor_t* tensor);
extern   int64_t msml_tensor_rank(const msml_tensor_t* tensor);
extern   const int64_t* msml_tensor_shape(const msml_tensor_t* tensor);
extern   const int64_t* msml_tensor_strides(const msml_tensor_t* tensor);
extern   msml_dtype_t msml_tensor_dtype(const msml_tensor_t* tensor);
extern   void* msml_tensor_buf(const msml_tensor_t* tensor);
extern   float* msml_tensor_buf_f32(const msml_tensor_t* tensor);
extern   int64_t msml_tensor_buf_size(const msml_tensor_t* tensor);
extern   int64_t msml_tensor_buf_len(const msml_tensor_t* tensor);
extern   int64_t msml_tensor_num_rows(const msml_tensor_t* tensor);
extern   int64_t msml_tensor_num_cols(const msml_tensor_t* tensor);
extern   bool msml_tensor_is_scalar(const msml_tensor_t* tensor);
extern   bool msml_tensor_is_vector(const msml_tensor_t* tensor);
extern   bool msml_tensor_is_matrix(const msml_tensor_t* tensor);
extern   bool msml_tensor_is_higher_order_3d(const msml_tensor_t* tensor);
extern   bool msml_tensor_is_shape_eq(const msml_tensor_t* a, const msml_tensor_t* b);
extern   bool msml_tensor_are_strides_eq(const msml_tensor_t* a, const msml_tensor_t* b);
extern   bool msml_tensor_can_broadcast(const msml_tensor_t* a, const msml_tensor_t* b);
extern   bool msml_tensor_is_transposed(const msml_tensor_t* tensor);
extern   void msml_tensor_virtual_to_physical_index(const msml_tensor_t* tensor, int64_t v_idx, int64_t(*p_idx)[4]);
extern   int64_t msml_tensor_physical_to_virtual_index(const msml_tensor_t* tensor, const int64_t(*p_idx)[4]);
extern   bool msml_tensor_is_contiguous(const msml_tensor_t* tensor);
extern   float msml_tensor_get_scalar_physical_index(const msml_tensor_t* tensor, int64_t d0, int64_t d1, int64_t d2, int64_t d3);
extern   void msml_tensor_set_scalar_physical_index(msml_tensor_t* tensor, int64_t d0, int64_t d1, int64_t d2, int64_t d3, float x);
extern   float msml_tensor_get_scalar_virtual_index(const msml_tensor_t* tensor, int64_t v_idx);
extern   void msml_tensor_set_scalar_virtual_index(msml_tensor_t* tensor, int64_t v_idx, float x);
extern   bool msml_tensor_eq(const msml_tensor_t* a, const msml_tensor_t* b);
extern   bool msml_tensor_is_close(const msml_tensor_t* a, const msml_tensor_t* b, float eps, double* percent_eq);
extern   msml_ctx_t* msml_tensor_get_ctx(const msml_tensor_t* tensor);
extern   void msml_tensor_save(const msml_tensor_t* tensor, const char* file_name);
extern   msml_tensor_t* msml_tensor_load(msml_ctx_t* ctx, const char* file_name);
extern   msml_tensor_t* msml_tensor_create_from_image(msml_ctx_t* ctx, const char* file_path, msml_desired_color_channels_t channels, uint32_t resize_width, uint32_t resize_height);
extern   void msml_tensor_save_to_image(const msml_tensor_t* tensor, const char* file_path);
extern   msml_compute_graph_t* msml_compute_graph_compile(msml_ctx_t* ctx, msml_tensor_t* root, msml_graph_eval_order_t order, const char* name);
extern   msml_tensor_t* msml_compute_graph_execute(msml_compute_graph_t* gra);
extern   bool msml_compute_graph_contains(const msml_compute_graph_t* gra, const msml_tensor_t* tensor);
extern   void msml_compute_graph_dump_to_dot(const msml_compute_graph_t* gra, const char* file_name);
extern   msml_ctx_t* msml_compute_graph_get_ctx(const msml_compute_graph_t* gra);
extern   const char* msml_compute_graph_get_name(const msml_compute_graph_t* gra);
extern   const msml_tensor_t** msml_compute_graph_get_internal_nodes(const msml_compute_graph_t* gra, size_t* n_nodes);
extern   const msml_tensor_t** msml_compute_graph_get_leaf_nodes(const msml_compute_graph_t* gra, size_t* n_leaves);
extern   size_t msml_compute_graph_get_num_total_nodes(const msml_compute_graph_t* gra);
extern   size_t msml_compute_graph_get_num_internal_nodes(const msml_compute_graph_t* graph);
extern   size_t msml_compute_graph_get_num_leaf_nodes(const msml_compute_graph_t* gra);
extern   size_t msml_compute_graph_get_order(const msml_compute_graph_t* gra);
extern   size_t msml_compute_graph_get_memory_usage(const msml_compute_graph_t* gra);
'''

