# Autogenered by /Users/mario/Documents/projects/wavelet/python/wavelet/_ffi_cdecl_generator.py 2024-11-11 12:29:20.315484, do NOT edit!

__WL_CDECLS: str = '''

typedef struct wl_ctx_info_t wl_ctx_info_t;
typedef struct wl_ctx_t wl_ctx_t;
typedef struct wl_dtype_info_t wl_dtype_info_t;
typedef struct wl_tensor_t wl_tensor_t;
typedef struct wl_compute_graph_t wl_compute_graph_t;

typedef int wl_exec_mode_t;
typedef int wl_prng_algorithm_t;
typedef int wl_color_channels_t;
typedef int wl_dtype_t;
typedef int wl_op_t;
typedef int wl_op_param_type_t;
typedef int wl_graph_eval_order_t;

extern   void* (*wl_get_alloc_fn(void))(void* blk, size_t size);
extern   void wl_set_alloc_fn(void* (*alloc)(void* blk, size_t size));
extern   wl_ctx_t* wl_ctx_create(const wl_ctx_info_t* info);
extern   wl_ctx_t* wl_ctx_create2(size_t pool_chunk_size);
extern   void* wl_ctx_pool_alloc(wl_ctx_t* ctx, size_t size);
extern   void* wl_ctx_pool_alloc_aligned(wl_ctx_t* ctx, size_t size, size_t align);
extern   size_t wl_ctx_total_allocated_pool_memory(const wl_ctx_t* ctx);
extern   wl_exec_mode_t wl_ctx_get_exec_mode(const wl_ctx_t* ctx);
extern   void wl_ctx_set_exec_mode(wl_ctx_t* ctx, wl_exec_mode_t mode);
extern   wl_prng_algorithm_t wl_ctx_get_prng_algorithm(const wl_ctx_t* ctx);
extern   void wl_ctx_set_prng_algorithm(wl_ctx_t* ctx, wl_prng_algorithm_t algorithm, uint64_t seed);
extern   const char* wl_ctx_get_os_name(const wl_ctx_t* ctx);
extern   const char* wl_ctx_get_cpu_name(const wl_ctx_t* ctx);
extern   uint32_t wl_ctx_get_cpu_virtual_cores(const wl_ctx_t* ctx);
extern   uint32_t wl_ctx_get_cpu_physical_cores(const wl_ctx_t* ctx);
extern   uint32_t wl_ctx_get_cpu_sockets(const wl_ctx_t* ctx);
extern   uint64_t wl_ctx_get_physical_memory_total(const wl_ctx_t* ctx);
extern   uint64_t wl_ctx_get_physical_memory_free(const wl_ctx_t* ctx);
extern   bool wl_ctx_is_numa_system(const wl_ctx_t* ctx);
extern   size_t wl_ctx_get_total_tensors_created(const wl_ctx_t* ctx);
extern   size_t wl_ctx_get_total_tensors_allocated(const wl_ctx_t* ctx);
extern   void wl_ctx_profile_start_recording(wl_ctx_t* ctx);
extern   void wl_ctx_profile_stop_recording(wl_ctx_t* ctx, const char* export_csv_file);
extern   void wl_ctx_destroy(wl_ctx_t* ctx);
extern   const wl_dtype_info_t* wl_dtype_info_of(wl_dtype_t type);
extern   const char* wl_op_get_name(wl_op_t op);
extern   const char* wl_op_get_mnemonic(wl_op_t op);
extern   uint8_t wl_op_get_argcount(wl_op_t op);
extern   uint8_t wl_op_get_paramcount(wl_op_t op);
extern   bool wl_op_supports_inplace(wl_op_t op);
typedef uint64_t wl_op_param_t;
extern   wl_op_param_t wl_op_param_int(uint32_t x);
extern   bool wl_op_param_is_int(wl_op_param_t param);
extern   uint32_t wl_op_param_unpack_int(wl_op_param_t param);
extern   wl_op_param_t wl_op_param_float(float x);
extern   bool wl_op_param_is_float(wl_op_param_t param);
extern   float wl_op_param_unpack_float(wl_op_param_t param);
extern   uint32_t wl_pack_color_u8(uint8_t r, uint8_t g, uint8_t b);
extern   uint32_t wl_pack_color_f32(float r, float g, float b);
extern   wl_tensor_t* wl_tensor_create_1d(wl_ctx_t* ctx, wl_dtype_t type, int64_t d1);
extern   wl_tensor_t* wl_tensor_create_2d(wl_ctx_t* ctx, wl_dtype_t type, int64_t d1, int64_t d2);
extern   wl_tensor_t* wl_tensor_create_3d(wl_ctx_t* ctx, wl_dtype_t type, int64_t d1, int64_t d2, int64_t d3);
extern   wl_tensor_t* wl_tensor_create_4d(wl_ctx_t* ctx, wl_dtype_t type, int64_t d1, int64_t d2, int64_t d3, int64_t d4);
extern   wl_tensor_t* wl_tensor_create_5d(wl_ctx_t* ctx, wl_dtype_t type, int64_t d1, int64_t d2, int64_t d3, int64_t d4, int64_t d5);
extern   wl_tensor_t* wl_tensor_create_6d(wl_ctx_t* ctx, wl_dtype_t type, int64_t d1, int64_t d2, int64_t d3, int64_t d4, int64_t d5, int64_t d6);
extern   wl_tensor_t* wl_tensor_operator(wl_ctx_t* ctx, wl_op_t op, bool inplace, wl_tensor_t** inputs, uint32_t n_inputs, const wl_op_param_t(*params)[6]);
extern   void wl_tensor_copy_buffer_from(wl_tensor_t* t, const void* data, size_t size);
extern   void wl_tensor_fill(wl_tensor_t* t, float x);
extern   void wl_tensor_fill_random(wl_tensor_t* t, float min, float max);
extern   size_t wl_tensor_get_memory_usage(const wl_tensor_t* t);
extern   void wl_tensor_print(const wl_tensor_t* t, bool with_header, bool with_data);
extern   void wl_tensor_set_name(wl_tensor_t* t, const char* name);
extern   void wl_tensor_fmt_name(wl_tensor_t* t, const char* fmt, ...);
extern   const char* wl_tensor_get_name(const wl_tensor_t* t);
extern   int64_t wl_tensor_rank(const wl_tensor_t* t);
extern   const int64_t* wl_tensor_shape(const wl_tensor_t* t);
extern   const int64_t* wl_tensor_strides(const wl_tensor_t* t);
extern   wl_dtype_t wl_tensor_dtype(const wl_tensor_t* t);
extern   void* wl_tensor_data(const wl_tensor_t* t);
extern   float* wl_tensor_data_as_f32(const wl_tensor_t* t);
extern   int64_t wl_tensor_data_size(const wl_tensor_t* t);
extern   int64_t wl_tensor_num_elements(const wl_tensor_t* t);
extern   int64_t wl_tensor_num_rows(const wl_tensor_t* t);
extern   int64_t wl_tensor_num_cols(const wl_tensor_t* t);
extern   bool wl_tensor_is_scalar(const wl_tensor_t* t);
extern   bool wl_tensor_is_vector(const wl_tensor_t* t);
extern   bool wl_tensor_is_matrix(const wl_tensor_t* t);
extern   bool wl_tensor_is_volume(const wl_tensor_t* t);
extern   bool wl_tensor_is_shape_eq(const wl_tensor_t* a, const wl_tensor_t* b);
extern   bool wl_tensor_are_strides_eq(const wl_tensor_t* a, const wl_tensor_t* b);
extern   bool wl_tensor_can_broadcast(const wl_tensor_t* a, const wl_tensor_t* b);
extern   bool wl_tensor_is_transposed(const wl_tensor_t* t);
extern   bool wl_tensor_is_permuted(const wl_tensor_t* t);
extern   bool wl_tensor_is_contiguous(const wl_tensor_t* t);
extern   float wl_tensor_get_scalar_physical_index(const wl_tensor_t* t, int64_t d0, int64_t d1, int64_t d2, int64_t d3, int64_t d4, int64_t d5);
extern   void wl_tensor_set_scalar_physical_index(wl_tensor_t* t, int64_t d0, int64_t d1, int64_t d2, int64_t d3, int64_t d4, int64_t d5, float x);
extern   float wl_tensor_get_scalar_virtual_index(const wl_tensor_t* t, int64_t v_idx);
extern   void wl_tensor_set_scalar_virtual_index(wl_tensor_t* t, int64_t v_idx, float x);
extern   bool wl_tensor_eq(const wl_tensor_t* a, const wl_tensor_t* b);
extern   bool wl_tensor_is_close(const wl_tensor_t* a, const wl_tensor_t* b, float eps, double* percent_eq);
extern   void wl_tensor_img_draw_box(wl_tensor_t* t, uint32_t x1, uint32_t y1, uint32_t x2, uint32_t y2, uint32_t wi, uint32_t rgb);
extern   wl_ctx_t* wl_tensor_get_ctx(const wl_tensor_t* t);
extern   void* wl_tensor_get_user_data(const wl_tensor_t* t);
extern   void wl_tensor_set_user_data(wl_tensor_t* t, void* ud);
extern   void wl_tensor_save(const wl_tensor_t* t, const char* file);
extern   wl_tensor_t* wl_tensor_load(wl_ctx_t* ctx, const char* file);
extern   wl_tensor_t* wl_tensor_load_image(wl_ctx_t* ctx, const char* file, wl_color_channels_t channels, uint32_t resize_w, uint32_t resize_h);
extern   void wl_tensor_save_image(const wl_tensor_t* t, const char* file);
extern   wl_compute_graph_t* wl_compute_graph_compile(wl_ctx_t* ctx, wl_tensor_t* root, wl_graph_eval_order_t order, const char* name);
extern   wl_tensor_t* wl_compute_graph_execute(wl_compute_graph_t* gra);
extern   bool wl_compute_graph_contains(const wl_compute_graph_t* gra, const wl_tensor_t* t);
extern   void wl_compute_graph_dump_to_dot(const wl_compute_graph_t* gra, const char* file_name);
extern   wl_ctx_t* wl_compute_graph_get_ctx(const wl_compute_graph_t* gra);
extern   const char* wl_compute_graph_get_name(const wl_compute_graph_t* gra);
extern   const wl_tensor_t** wl_compute_graph_get_internal_nodes(const wl_compute_graph_t* gra, size_t* n_nodes);
extern   const wl_tensor_t** wl_compute_graph_get_leaf_nodes(const wl_compute_graph_t* gra, size_t* n_leaves);
extern   size_t wl_compute_graph_get_num_total_nodes(const wl_compute_graph_t* gra);
extern   size_t wl_compute_graph_get_num_internal_nodes(const wl_compute_graph_t* graph);
extern   size_t wl_compute_graph_get_num_leaf_nodes(const wl_compute_graph_t* gra);
extern   size_t wl_compute_graph_get_order(const wl_compute_graph_t* gra);
extern   size_t wl_compute_graph_get_memory_usage(const wl_compute_graph_t* gra);
'''

